language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=^8.7.0

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION=^8.7.0
    - php: 5.6
      env: TYPO3_VERSION=^8.7.0

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - patrick.schriner@diemedialen.de

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"
  - export PATH="$PATH:./Scripts"
  - if [ -d .Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build ]; then export TYPO3_BUILD_DIR=".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build"; else export TYPO3_BUILD_DIR=".Build/vendor/typo3/cms/typo3/sysext/core/Build"; fi

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c $TYPO3_BUILD_DIR/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
