language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION="^6.2.0"
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.7.0"

matrix:
  exclude:
    - php: 7
      env: TYPO3_VERSION="^6.2.0"
    - php: 5.5
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.6
      env: TYPO3_VERSION="^8.7.0"

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - patrick.schriner@diemedialen.de

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - git clean -dffx
  - composer require typo3/cms="$TYPO3_VERSION"
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
