language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=dev-master

matrix:
  allow_failures:
    - env: TYPO3_VERSION=dev-master
  exclude:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
    - php: 5.6
      env: TYPO3_VERSION=dev-master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - patrick.schriner@diemedialen.de

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;